get_filename_component(_xf_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
    message(FATAL_ERROR "This package contains x86-64 binaries only.")
endif()
foreach(_xf_part swarm eots)
    if(NOT TARGET XF::${_xf_part})
        add_library(XF::${_xf_part} SHARED IMPORTED)
        set_target_properties(XF::${_xf_part} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_xf_root}/include")
        if(WIN32)
            set(_xf_dir "${_xf_root}/lib/windows-x86_64")
            set_target_properties(XF::${_xf_part} PROPERTIES IMPORTED_LOCATION "${_xf_dir}/xf_${_xf_part}.dll")
            if(MSVC)
                if(NOT EXISTS "${_xf_dir}/xf_${_xf_part}.lib")
                    message(FATAL_ERROR "Generate MSVC import libraries from the supplied .def files first; see README.")
                endif()
                set_target_properties(XF::${_xf_part} PROPERTIES IMPORTED_IMPLIB "${_xf_dir}/xf_${_xf_part}.lib")
            else()
                set_target_properties(XF::${_xf_part} PROPERTIES IMPORTED_IMPLIB "${_xf_dir}/libxf_${_xf_part}.dll.a")
            endif()
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            set_target_properties(XF::${_xf_part} PROPERTIES IMPORTED_LOCATION "${_xf_root}/lib/linux-x86_64/xf_${_xf_part}.so")
        else()
            message(FATAL_ERROR "Only Windows and Linux are supported by this binary package.")
        endif()
    endif()
endforeach()
set(XFSwarm_VERSION 1.0.0)
